# Generated by Django 2.2.2 on 2019-07-05 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Autor',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombres', models.CharField(max_length=255, verbose_name='Nombres del autor')),
                ('apellidos', models.CharField(max_length=255, verbose_name='Apellidos del autor')),
                ('direccion_facebook', models.URLField(blank=True, null=True, verbose_name='Facebook')),
                ('direccion_twitter', models.URLField(blank=True, null=True, verbose_name='Twitter')),
                ('direccion_instagram', models.URLField(blank=True, null=True, verbose_name='Instagram')),
                ('direccion_web', models.URLField(blank=True, null=True, verbose_name='Blog Personal')),
                ('correo', models.EmailField(max_length=254, verbose_name='Correo electronico')),
                ('estado', models.BooleanField(default=True, verbose_name='Autor Activo / Autor no activo')),
                ('fecha_creacion', models.DateField(auto_now_add=True, verbose_name='Fecha de creacion')),
            ],
            options={
                'verbose_name': 'Autor',
                'verbose_name_plural': 'Autores',
            },
        ),
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre Categoria')),
                ('estado', models.BooleanField(default=True, verbose_name='Caterogia activada/Categoria desactivada')),
                ('fecha_creacion', models.DateField(auto_now_add=True, verbose_name='Fecha de creacion')),
            ],
            options={
                'verbose_name': 'Categoria',
                'verbose_name_plural': 'Categorias',
            },
        ),
    ]
