# Generated by Django 2.2.2 on 2019-07-19 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_libro'),
    ]

    operations = [
        migrations.AlterField(
            model_name='libro',
            name='book_desc',
            field=models.CharField(blank=True, max_length=900, null=True, verbose_name='Descripcion libro'),
        ),
    ]
