# Generated by Django 2.2.2 on 2019-07-19 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20190718_2353'),
    ]

    operations = [
        migrations.AlterField(
            model_name='libro',
            name='book_desc',
            field=models.CharField(blank=True, max_length=1100, null=True, verbose_name='Descripcion libro'),
        ),
    ]
